development:
  secret_key_base: YOUR_FIRST_RAILS_SECRET_STRING_HERE

test:
  secret_key_base: YOUR_SECOND_RAILS_SECRET_STRING_HERE

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
